### ISSUE TITLE
Globe Anchor Doesn't Support Prefab Overrides

### ISSUE THREAD

**Issue by Waffle1434** [CesiumGS/cesium-unity#335]
If the `CesiumGlobeAnchor` component is on a GameObject in a prefab, the prefab's world coordinates will always be used regardless of coordinate overrides for prefab instances.

For example, I have a prefab of a helicopter with a world anchor:
![image](https://github.com/CesiumGS/cesium-unity/assets/8021358/7e813688-77ba-4032-bee0-8e50d522a0c1)
It has a default coordinate of `33.4588218, -111.72937073` because that's where I originally made it a prefab.

If I place multiple instances of the prefab, all instances will revert back to this coordinate either when "Play" mode enters, or the scene is reloaded:
![image](https://github.com/CesiumGS/cesium-unity/assets/8021358/9dc62812-f3ba-4bb2-9faa-ed2abc01ea5b)

Two helicopters now overlapping at the same coordinate after play/reload:
![image](https://github.com/CesiumGS/cesium-unity/assets/8021358/485e81a2-3a55-40f0-b714-3c3133b8636b)

Notice how `Scale` has a blue highlight showing its an override, while the globe anchor has nothing marked as changed:
![image](https://github.com/CesiumGS/cesium-unity/assets/8021358/e1359401-8d05-4737-becc-c260a4102816)

I fixed the issue for now by not including the anchor in the prefab, and I manually add the anchor to each instance.

**Comment by kring** [comment]
This is a tricky one.

If you put the anchored object inside the CesiumGeoreference, and _then_ modify its Transform, the CesiumGlobeAnchor position will update accordingly. And should remember its position from then on.

But if you don't explicitly set the position (_after_ it's nested inside the CesiumGeoreference!), then the CesiumGlobeAnchor thinks that it has an authoritative ECEF position, and it overwrites the transform with one computed from that ECEF position.

Basically the Transform position needs to be set last, and all would be well. But when it's set too early (before the component is enabled, or before it's nested in the CesiumGeoreference), then the position inherited from the prefab is deemed accurate. When you call Instantiate and pass a position, that ends up setting the position too early.

I'm not quite sure what we can do about this. Perhaps if Unity sends some message to the component when it is created from a prefab? But I don't see one. The only other thing I can think of is to serialize the "last known" position, so we can detect a change in it even if a new position is already set by the time OnEnable is called. That will make the object a bit bigger, of course, but I'll have to think through whether there are any more serious consequences of this.

But as a workaround, can you try simply setting the position again after the `Instantiate` call returns?

**Comment by Waffle1434** [comment]
In this case I'm not calling `GameObject.Instantiate`.
I have a scene with multiple prefab instances hand-placed as children of the georeference at edit-time, and I save the scene. They have only existed as children of the Georeference.
![image](https://github.com/CesiumGS/cesium-unity/assets/8021358/921bb040-3d8d-4920-82b3-bbaca5255c98)

It is *as if* the ECEF positions aren't being saved in the scene file for prefab instances, so when de-serialized the component has no idea it shouldn't use the prefab's default.

If the prefab doesn't contain an anchor, and I add it manually in the scene (my workaround), the `_localToGlobeFixedMatrix` is serialized inside the `.unity` file and it loads correctly:
```YAML
PrefabInstance:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Modification:
    m_TransformParent: {fileID: 666272557}
    m_Modifications:
    - target: {fileID: 319014584688397647, guid: 724ba02cd68e7ca478e49f54efb04ea1,
        type: 3}
      propertyPath: m_Name
      value: AH-64D Cesium (1)
      objectReference: {fileID: 0}
...
MonoBehaviour:
...
  _adjustOrientationForGlobeWhenMoving: 1
  _detectTransformChanges: 1
  _localToGlobeFixedMatrix:
    c0:
      x: 0.6676539270647021
      y: -1.2620902257691409
      z: -1.4004906604188934
      w: 0
    c1:
      x: -0.6175723941958005
      y: -1.5501564798246226
      z: 1.102551235083885
      w: 0
    c2:
      x: 1.7812494046963758
      y: -0.0643908541531326
      z: 0.9072000718682209
      w: 0
    c3:
      x: -1972096.133820307
      y: -4948730.1963643925
      z: 3496569.9432099764
      w: 1
  _localToGlobeFixedMatrixIsValid: 1
```

If I try moving an instance around with the anchor inside the prefab, its never written to the scene. `m_Modifications` should have an entry for `_localToGlobeFixedMatrixIsValid` but it doesn't. Unity is storing modifications/overrides for the Transform's XYZ position though (of course, ignored by Cesium by design). When the scene is played or reloaded, it will use the prefab's default coordinates because no modification in the scene file says otherwise:
```YAML
PrefabInstance:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Modification:
    m_TransformParent: {fileID: 666272557}
    m_Modifications:
    - target: {fileID: 319014584688397647, guid: 724ba02cd68e7ca478e49f54efb04ea1,
        type: 3}
      propertyPath: m_Name
      value: AH-64D Cesium
      objectReference: {fileID: 0}
...
      propertyPath: m_LocalPosition.x
      value: -348.56
      objectReference: {fileID: 0}
    - target: {fileID: 1091716913026111477, guid: 724ba02cd68e7ca478e49f54efb04ea1,
        type: 3}
      propertyPath: m_LocalPosition.y
      value: 20.17
      objectReference: {fileID: 0}
    - target: {fileID: 1091716913026111477, guid: 724ba02cd68e7ca478e49f54efb04ea1,
        type: 3}
      propertyPath: m_LocalPosition.z
      value: -128.88
      objectReference: {fileID: 0}
...
  m_SourcePrefab: {fileID: 100100000, guid: 724ba02cd68e7ca478e49f54efb04ea1, type: 3}
--- !u!4 &1261796114 stripped
Transform:
  m_CorrespondingSourceObject: {fileID: 1091716913026111477, guid: 724ba02cd68e7ca478e49f54efb04ea1,
    type: 3}
  m_PrefabInstance: {fileID: 1261796113}
  m_PrefabAsset: {fileID: 0}
```

From Cesium's perspective, in scene edit-time I'm moving the helicopter around the scene and its recalculating the ECEF. However, its not saving it anywhere for some reason when its a prefab instance. I don't think there's anything you can do in regards to being notified, it needs to be fixed at serialization-time.
